FROM node:22-alpine AS builder
WORKDIR /usr/src/app
COPY package*.json tsconfig*.json ./
RUN npm ci --include=dev && npm cache clean --force
COPY . .
RUN npm run build && \
    rm -rf src test node_modules && \
    npm ci --only=production

FROM node:22-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .
EXPOSE 5001
USER node
CMD ["node", "dist/main"]